const $=s=>document.querySelector(s);const pad=n=>String(n).padStart(2,'0');
const today=new Date();today.setHours(0,0,0,0);const initialReplace=new Date(today);initialReplace.setDate(today.getDate()+4);
const state={replaceDate:initialReplace,available:[],skill:'Голосовая поддержка L1',custom:false,viewReplace:new Date(today.getFullYear(),today.getMonth(),1),viewAvailable:new Date(today.getFullYear(),today.getMonth(),1)};
const months=['январь','февраль','март','апрель','май','июнь','июль','август','сентябрь','октябрь','ноябрь','декабрь'];
const fmt=d=>`${pad(d.getDate())}.${pad(d.getMonth()+1)}.${String(d.getFullYear()).slice(-2)}`;const key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
function monthMarkup(view,selected,multi=false){const y=view.getFullYear(),m=view.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();let html=`<div class="calendar-header"><button class="calendar-nav prev" type="button" aria-label="Предыдущий месяц">‹</button><div class="calendar-title">${months[m]} ${y}</div><button class="calendar-nav next" type="button" aria-label="Следующий месяц">›</button></div><div class="calendar-grid">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<span class="weekday">${x}</span>`).join('')}`;for(let i=0;i<first;i++)html+='<span></span>';for(let d=1;d<=days;d++){const date=new Date(y,m,d),isPast=date<today,isSelected=multi?selected.includes(key(date)):selected&&key(date)===key(selected);html+=`<button type="button" class="day ${isSelected?'selected':''} ${key(date)===key(today)?'today':''} ${isPast?'disabled':''}" data-date="${key(date)}" ${isPast?'disabled':''}>${d}</button>`}return html+'</div>'}
function parseDate(v){const [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)}
function bindCalendar(root,type){root.querySelector('.prev').onclick=()=>{state[type].setMonth(state[type].getMonth()-1);renderCalendars()};root.querySelector('.next').onclick=()=>{state[type].setMonth(state[type].getMonth()+1);renderCalendars()};root.querySelectorAll('.day:not(.disabled)').forEach(b=>b.onclick=()=>{const d=parseDate(b.dataset.date);if(type==='viewReplace'){state.replaceDate=d;$('#replaceCalendar').hidden=true}else{const k=key(d),i=state.available.indexOf(k);i>=0?state.available.splice(i,1):state.available.push(k);state.available.sort()}renderCalendars();drawCard();save()})}
function renderCalendars(){const pop=$('#replaceCalendar'),inline=$('#availableCalendar');pop.innerHTML=monthMarkup(state.viewReplace,state.replaceDate);inline.innerHTML=monthMarkup(state.viewAvailable,state.available,true);bindCalendar(pop,'viewReplace');bindCalendar(inline,'viewAvailable');$('#replaceDateText').textContent=state.replaceDate?new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(state.replaceDate):'Выберите дату';const n=state.available.length;$('#dateCounter').textContent=`${n} ${n===1?'выбрано':'выбрано'}`}
$('#replaceDateButton').onclick=()=>$('#replaceCalendar').hidden=!$('#replaceCalendar').hidden;document.addEventListener('click',e=>{if(!e.target.closest('.field'))$('#replaceCalendar').hidden=true});
$('#skillOptions').onclick=e=>{const b=e.target.closest('.skill-option');if(!b)return;document.querySelectorAll('.skill-option').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.custom=b.id==='customSkillButton';$('#customSkillWrap').hidden=!state.custom;state.skill=state.custom?($('#customSkill').value||'Свой навык'):b.dataset.skill;drawCard();save()};
['startTime','endTime','username','note','customSkill'].forEach(id=>$('#'+id).addEventListener('input',()=>{if(id==='customSkill'&&state.custom)state.skill=$('#customSkill').value||'Свой навык';drawCard();save()}));
function rounded(ctx,x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function iconCircle(ctx,x,y,emoji){ctx.beginPath();ctx.arc(x,y,38,0,Math.PI*2);ctx.fillStyle='#fff4ce';ctx.fill();ctx.font='34px Arial';ctx.textAlign='center';ctx.fillStyle='#111';ctx.fillText(emoji,x,y+12)}
function fitText(ctx,text,max,width){let size=max;do{ctx.font=`700 ${size}px Manrope, Arial`;size--}while(ctx.measureText(text).width>width&&size>18);return size+1}
function drawCard(){const c=$('#cardCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#fffefb');g.addColorStop(1,'#f0efeb');rounded(ctx,0,0,w,h,30,g);ctx.textAlign='left';ctx.fillStyle='#f23b2b';ctx.font='800 53px Manrope, Arial';ctx.fillText('Y',60,74);ctx.fillStyle='#090909';ctx.fillText('andex',100,74);ctx.font='400 52px Manrope, Arial';ctx.fillText('Team',270,74);ctx.font='42px Arial';ctx.fillText('🎧',1080,72);
const yg=ctx.createLinearGradient(50,115,1150,250);yg.addColorStop(0,'#ffb800');yg.addColorStop(1,'#ffd747');rounded(ctx,45,112,1110,150,28,yg);rounded(ctx,70,135,108,105,24,'rgba(255,255,255,.25)');ctx.font='68px Arial';ctx.textAlign='center';ctx.fillText('↻',124,211);ctx.textAlign='left';ctx.fillStyle='#111';ctx.font='800 43px Manrope, Arial';ctx.fillText('Ищу замену',210,177);ctx.font='500 25px Manrope, Arial';ctx.fillText('на рабочий день',210,219);rounded(ctx,770,130,350,112,24,'#fffdfa');ctx.font='36px Arial';ctx.fillText('▦',805,198);ctx.font='800 39px Manrope, Arial';ctx.fillText(fmt(state.replaceDate),872,199);
rounded(ctx,45,282,1110,350,25,'#fff');const rows=[['🎧','Навык:',state.skill],['◷','Смена:',`${$('#startTime').value||'—'} – ${$('#endTime').value||'—'}`]];rows.forEach((r,i)=>{const y=350+i*104;iconCircle(ctx,105,y,r[0]);ctx.fillStyle='#111';ctx.font='800 22px Manrope, Arial';ctx.fillText(r[1],165,y-8);ctx.font=`600 ${fitText(ctx,r[2],25,600)}px Manrope, Arial`;ctx.fillText(r[2],165,y+30);ctx.strokeStyle='#efe3bb';ctx.beginPath();ctx.moveTo(165,y+55);ctx.lineTo(840,y+55);ctx.stroke()});iconCircle(ctx,105,557,'▦');ctx.font='800 22px Manrope, Arial';ctx.fillStyle='#111';ctx.fillText('Могу выйти в числа:',165,542);let x=165,y=563;const dates=state.available.slice(0,9).map(v=>parseDate(v).getDate());if(!dates.length){ctx.font='500 20px Manrope, Arial';ctx.fillStyle='#999';ctx.fillText('выберите даты в календаре',165,585)}else dates.forEach(n=>{rounded(ctx,x,y,62,46,12,'#fff','#f5b900');ctx.fillStyle='#111';ctx.textAlign='center';ctx.font='800 22px Manrope, Arial';ctx.fillText(n,x+31,y+31);ctx.textAlign='left';x+=72;if(x>760){x=165;y+=52}});
ctx.save();ctx.translate(973,470);ctx.rotate(.1);rounded(ctx,-100,-95,200,200,30,'#f3f0e9');rounded(ctx,-100,-95,200,58,28,'#ffc31a');ctx.fillStyle='#222';for(let i=-60;i<=60;i+=60){rounded(ctx,i-10,-115,20,55,10,'#171717')}ctx.beginPath();ctx.arc(0,25,55,0,Math.PI*2);ctx.fillStyle='#ffbd0b';ctx.fill();ctx.strokeStyle='white';ctx.lineWidth=13;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-24,25);ctx.lineTo(-5,45);ctx.lineTo(34,3);ctx.stroke();ctx.restore();
rounded(ctx,25,650,1150,86,28,'#202120');ctx.font='30px Arial';ctx.fillStyle='#ffcc00';ctx.fillText('☆',55,706);ctx.fillStyle='white';ctx.font=`600 ${fitText(ctx,$('#note').value||'Буду благодарен за обмен!',25,660)}px Manrope, Arial`;ctx.fillText($('#note').value||'Буду благодарен за обмен!',110,706);ctx.strokeStyle='#666';ctx.beginPath();ctx.moveTo(825,666);ctx.lineTo(825,720);ctx.stroke();ctx.font='26px Arial';ctx.fillStyle='#ffcc00';ctx.fillText('♙',855,705);ctx.fillStyle='white';ctx.font=`700 ${fitText(ctx,'@'+($('#username').value||'username'),23,245)}px Manrope, Arial`;ctx.fillText('@'+($('#username').value||'username'),900,705)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2300)}
$('#downloadButton').onclick=()=>{const a=document.createElement('a');a.download=`замена-${key(state.replaceDate)}.png`;a.href=$('#cardCanvas').toDataURL('image/png');a.click();toast('Карточка скачана')};
$('#copyButton').onclick=async()=>{try{const blob=await new Promise(r=>$('#cardCanvas').toBlob(r,'image/png'));await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);toast('Карточка скопирована')}catch{toast('Копирование не поддерживается — скачайте PNG')}};
function save(){localStorage.setItem('teamSwapState',JSON.stringify({replace:key(state.replaceDate),available:state.available,skill:state.skill,custom:state.custom,start:$('#startTime').value,end:$('#endTime').value,user:$('#username').value,note:$('#note').value,customSkill:$('#customSkill').value}))}
function load(){try{const s=JSON.parse(localStorage.getItem('teamSwapState'));if(!s)return;state.replaceDate=parseDate(s.replace);state.available=s.available||[];state.skill=s.skill||state.skill;state.custom=!!s.custom;$('#startTime').value=s.start||'11:00';$('#endTime').value=s.end||'23:00';$('#username').value=s.user||'malinovskym';$('#note').value=s.note||'';$('#customSkill').value=s.customSkill||'';if(state.custom){$('#customSkillWrap').hidden=false;document.querySelectorAll('.skill-option').forEach(x=>x.classList.remove('active'));$('#customSkillButton').classList.add('active')}}catch{}}
$('#resetButton').onclick=()=>{localStorage.removeItem('teamSwapState');location.reload()};load();renderCalendars();document.fonts.ready.then(drawCard);drawCard();
