const $=s=>document.querySelector(s);const pad=n=>String(n).padStart(2,'0');
const today=new Date();today.setHours(0,0,0,0);const initialReplace=new Date(today);initialReplace.setDate(today.getDate()+4);
const state={replaceDate:initialReplace,available:[],skills:['Голосовая поддержка L1'],customSkills:[],customOpen:false,viewReplace:new Date(today.getFullYear(),today.getMonth(),1),viewAvailable:new Date(today.getFullYear(),today.getMonth(),1)};
const months=['январь','февраль','март','апрель','май','июнь','июль','август','сентябрь','октябрь','ноябрь','декабрь'];
const fmt=d=>`${pad(d.getDate())}.${pad(d.getMonth()+1)}.${String(d.getFullYear()).slice(-2)}`;const key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
function monthMarkup(view,selected,multi=false){const y=view.getFullYear(),m=view.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();let html=`<div class="calendar-header"><button class="calendar-nav prev" type="button" aria-label="Предыдущий месяц">‹</button><div class="calendar-title">${months[m]} ${y}</div><button class="calendar-nav next" type="button" aria-label="Следующий месяц">›</button></div><div class="calendar-grid">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<span class="weekday">${x}</span>`).join('')}`;for(let i=0;i<first;i++)html+='<span></span>';for(let d=1;d<=days;d++){const date=new Date(y,m,d),isPast=date<today,isSelected=multi?selected.includes(key(date)):selected&&key(date)===key(selected);html+=`<button type="button" class="day ${isSelected?'selected':''} ${key(date)===key(today)?'today':''} ${isPast?'disabled':''}" data-date="${key(date)}" ${isPast?'disabled':''}>${d}</button>`}return html+'</div>'}
function parseDate(v){const [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)}
function bindCalendar(root,type){root.querySelector('.prev').onclick=()=>{state[type].setMonth(state[type].getMonth()-1);renderCalendars()};root.querySelector('.next').onclick=()=>{state[type].setMonth(state[type].getMonth()+1);renderCalendars()};root.querySelectorAll('.day:not(.disabled)').forEach(b=>b.onclick=()=>{const d=parseDate(b.dataset.date);if(type==='viewReplace'){state.replaceDate=d;$('#replaceCalendar').hidden=true}else{const k=key(d),i=state.available.indexOf(k);i>=0?state.available.splice(i,1):state.available.push(k);state.available.sort()}renderCalendars();drawCard();save()})}
function dateLabel(date,withYear=false){return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',...(withYear?{year:'numeric'}:{})}).format(date).replace('.','')}
function renderCalendars(){const pop=$('#replaceCalendar'),inline=$('#availableCalendar');pop.innerHTML=monthMarkup(state.viewReplace,state.replaceDate);inline.innerHTML=monthMarkup(state.viewAvailable,state.available,true);bindCalendar(pop,'viewReplace');bindCalendar(inline,'viewAvailable');$('#replaceDateText').textContent=new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(state.replaceDate);$('#dateCounter').textContent=`${state.available.length} выбрано`;const years=new Set(state.available.map(v=>parseDate(v).getFullYear()));$('#selectedDateList').innerHTML=state.available.length?state.available.map(v=>{const d=parseDate(v);return `<span class="selected-date-chip"><strong>${pad(d.getDate())}</strong>${months[d.getMonth()]}${years.size>1?` ${d.getFullYear()}`:''}</span>`}).join(''):'<span class="selected-date-empty">Выбранные даты появятся здесь</span>'}
$('#replaceDateButton').onclick=()=>$('#replaceCalendar').hidden=!$('#replaceCalendar').hidden;document.addEventListener('click',e=>{const path=e.composedPath();if(!path.includes($('#replaceCalendar'))&&!path.includes($('#replaceDateButton')))$('#replaceCalendar').hidden=true});
function syncSkills(){document.querySelectorAll('[data-skill]').forEach(b=>b.classList.toggle('active',state.skills.includes(b.dataset.skill)));$('#customSkillButton').classList.toggle('active',state.customOpen||state.customSkills.length>0);$('#customSkillWrap').hidden=!state.customOpen;$('#customSkillList').innerHTML=state.customSkills.map((s,i)=>`<button type="button" class="custom-skill-tag" data-index="${i}" title="Удалить">${s}</button>`).join('');drawCard();save()}
$('#skillOptions').onclick=e=>{const b=e.target.closest('.skill-option');if(!b)return;if(b.id==='customSkillButton'){state.customOpen=!state.customOpen}else{const s=b.dataset.skill,i=state.skills.indexOf(s);i>=0?state.skills.splice(i,1):state.skills.push(s)}syncSkills()};
function addCustom(){const input=$('#customSkill'),v=input.value.trim();if(v&&!state.customSkills.includes(v)){state.customSkills.push(v);input.value='';syncSkills()}}
$('#addCustomSkill').onclick=addCustom;$('#customSkill').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addCustom()}});$('#customSkillList').onclick=e=>{const b=e.target.closest('.custom-skill-tag');if(!b)return;state.customSkills.splice(Number(b.dataset.index),1);syncSkills()};
['startTime','endTime','username','note'].forEach(id=>$('#'+id).addEventListener('input',()=>{drawCard();save()}));
function rounded(ctx,x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function fitText(ctx,text,max,width,weight=700){let size=max;do{ctx.font=`${weight} ${size}px Manrope,Arial`;size--}while(ctx.measureText(text).width>width&&size>16);return size+1}
function wrapText(ctx,text,maxWidth,maxLines){const words=String(text).trim().split(/\s+/);const lines=[];let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width<=maxWidth){line=test}else{if(line)lines.push(line);line=word;if(lines.length===maxLines-1)break}}if(line&&lines.length<maxLines)lines.push(line);const used=lines.join(' ').length;if(used<text.length&&lines.length){let last=lines.length-1;while(ctx.measureText(lines[last]+'…').width>maxWidth&&lines[last].length>1)lines[last]=lines[last].slice(0,-1);lines[last]+='…'}return lines}
function drawAdaptiveText(ctx,text,x,y,width,{maxSize=25,minSize=15,maxLines=2,lineHeight=1.2,weight=700,color='#111'}={}){let size=maxSize,lines=[];for(;size>=minSize;size--){ctx.font=`${weight} ${size}px Manrope,Arial`;lines=wrapText(ctx,text,width,maxLines);if(lines.length<=maxLines&&lines.every(line=>ctx.measureText(line).width<=width))break}ctx.fillStyle=color;ctx.font=`${weight} ${size}px Manrope,Arial`;lines.forEach((line,i)=>ctx.fillText(line,x,y+i*size*lineHeight));return lines.length*size*lineHeight}
function lineIcon(ctx,type,x,y){ctx.save();ctx.translate(x,y);ctx.strokeStyle='#111';ctx.fillStyle='#111';ctx.lineWidth=5;ctx.lineCap='round';ctx.lineJoin='round';if(type==='headset'){ctx.beginPath();ctx.arc(0,0,25,Math.PI,0);ctx.stroke();ctx.strokeRect(-29,0,9,22);ctx.strokeRect(20,0,9,22);ctx.beginPath();ctx.moveTo(29,18);ctx.quadraticCurveTo(29,34,10,34);ctx.stroke();rounded(ctx,4,29,14,9,4,'#ffc400')}else if(type==='clock'){ctx.beginPath();ctx.arc(0,4,29,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(0,4);ctx.lineTo(0,-14);ctx.moveTo(0,4);ctx.lineTo(16,14);ctx.strokeStyle='#f5b900';ctx.stroke()}else{rounded(ctx,-27,-24,54,49,9,null,'#111');ctx.beginPath();ctx.moveTo(-15,-32);ctx.lineTo(-15,-17);ctx.moveTo(15,-32);ctx.lineTo(15,-17);ctx.stroke();ctx.fillStyle='#f5b900';[-13,0,13].forEach(dx=>ctx.fillRect(dx-3,-3,6,6));[-13,0,13].forEach(dx=>ctx.fillRect(dx-3,11,6,6))}ctx.restore()}
function drawCard(){const c=$('#cardCanvas'),ctx=c.getContext('2d'),allSkills=[...state.skills,...state.customSkills];ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#f4f3ef';ctx.fillRect(0,0,1200,760);rounded(ctx,20,20,1160,720,36,'#fff');ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.fillStyle='#f33';ctx.font='800 52px Manrope,Arial';ctx.fillText('Y',62,88);ctx.fillStyle='#111';ctx.fillText('andex',100,88);ctx.font='400 51px Manrope,Arial';ctx.fillText('Team',270,88);rounded(ctx,877,48,243,52,26,'#f4f3ef');ctx.fillStyle='#666';ctx.font='700 16px Manrope,Arial';ctx.fillText('ПРЕДЛОЖЕНИЕ ОБ ОБМЕНЕ',898,80);
const g=ctx.createLinearGradient(0,130,0,270);g.addColorStop(0,'#ffd53d');g.addColorStop(1,'#ffbd08');rounded(ctx,54,128,1092,142,26,g);ctx.fillStyle='#111';ctx.font='800 43px Manrope,Arial';ctx.fillText('Ищу замену',88,186);ctx.font='500 24px Manrope,Arial';ctx.fillText('на рабочий день',89,224);rounded(ctx,756,145,348,108,22,'#fff');lineIcon(ctx,'calendar',804,203);ctx.fillStyle='#8c887e';ctx.font='800 11px Manrope,Arial';ctx.fillText('ДАТА ЗАМЕНЫ',850,178);ctx.fillStyle='#111';ctx.font='800 38px Manrope,Arial';ctx.fillText(fmt(state.replaceDate),850,222);
rounded(ctx,54,290,1092,324,25,'#faf9f6');ctx.strokeStyle='#e5e2d8';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(105,403);ctx.lineTo(1095,403);ctx.moveTo(105,497);ctx.lineTo(1095,497);ctx.stroke();rounded(ctx,75,312,70,70,20,'#fff0ba');lineIcon(ctx,'headset',110,347);ctx.fillStyle='#89857a';ctx.font='800 14px Manrope,Arial';ctx.fillText('НАВЫКИ',174,332);drawAdaptiveText(ctx,allSkills.length?allSkills.join('  •  '):'Не выбраны',174,361,880,{maxSize:23,minSize:14,maxLines:2,lineHeight:1.15});rounded(ctx,75,415,70,70,20,'#fff0ba');lineIcon(ctx,'clock',110,447);ctx.fillStyle='#89857a';ctx.font='800 14px Manrope,Arial';ctx.fillText('СМЕНА',174,432);ctx.fillStyle='#111';ctx.font='700 25px Manrope,Arial';ctx.fillText(`${$('#startTime').value||'—'} — ${$('#endTime').value||'—'}`,174,469);
rounded(ctx,75,516,70,70,20,'#fff0ba');lineIcon(ctx,'calendar',110,552);ctx.fillStyle='#89857a';ctx.font='800 14px Manrope,Arial';ctx.fillText('МОГУ ВЫЙТИ',174,531);const dates=state.available.slice(0,8).map(v=>parseDate(v));if(!dates.length){ctx.fillStyle='#aaa';ctx.font='600 20px Manrope,Arial';ctx.fillText('Выберите даты в календаре',174,568)}else{let dx=174,dy=545;const showYear=new Set(dates.map(d=>d.getFullYear())).size>1;dates.forEach(d=>{const label=dateLabel(d,showYear);ctx.font='800 17px Manrope,Arial';const chipW=Math.max(82,ctx.measureText(label).width+24);if(dx+chipW>1080){dx=174;dy+=45}rounded(ctx,dx,dy,chipW,37,11,'#fff','#f5b900');ctx.fillStyle='#111';ctx.textAlign='center';ctx.fillText(label,dx+chipW/2,dy+25);ctx.textAlign='left';dx+=chipW+9})}rounded(ctx,54,632,1092,78,23,'#1e1f1d');ctx.fillStyle='#ffc800';ctx.font='30px Manrope,Arial';ctx.fillText('★',82,683);const note=$('#note').value||'Буду благодарен за обмен!';drawAdaptiveText(ctx,note,128,680,620,{maxSize:23,minSize:15,maxLines:1,weight:600,color:'#fff'});ctx.strokeStyle='#5b5c58';ctx.beginPath();ctx.moveTo(845,650);ctx.lineTo(845,692);ctx.stroke();ctx.fillStyle='#ffc800';ctx.font='25px Manrope,Arial';ctx.fillText('@',878,680);const user=$('#username').value||'username';drawAdaptiveText(ctx,user,912,680,195,{maxSize:22,minSize:15,maxLines:1,color:'#fff'});ctx.fillStyle='#aaa';ctx.font='500 9px Manrope,Arial';ctx.textAlign='center';ctx.fillText('НЕОФИЦИАЛЬНЫЙ ФАНАТСКИЙ ПРОЕКТ · НЕ СВЯЗАН С ЯНДЕКСОМ',600,728);ctx.textAlign='left'}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2300)}
$('#downloadButton').onclick=()=>{const a=document.createElement('a');a.download=`замена-${key(state.replaceDate)}.png`;a.href=$('#cardCanvas').toDataURL('image/png');a.click();toast('Карточка скачана')};$('#copyButton').onclick=async()=>{try{const blob=await new Promise(r=>$('#cardCanvas').toBlob(r,'image/png'));await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);toast('Карточка скопирована')}catch{toast('Копирование не поддерживается — скачайте PNG')}};
function save(){localStorage.setItem('teamSwapState',JSON.stringify({replace:key(state.replaceDate),available:state.available,skills:state.skills,customSkills:state.customSkills,start:$('#startTime').value,end:$('#endTime').value,user:$('#username').value,note:$('#note').value}))}
function load(){try{const s=JSON.parse(localStorage.getItem('teamSwapState'));if(!s)return;state.replaceDate=parseDate(s.replace);state.available=s.available||[];state.skills=s.skills||(s.skill?[s.skill]:state.skills);state.customSkills=s.customSkills||(s.customSkill?[s.customSkill]:[]);$('#startTime').value=s.start||'11:00';$('#endTime').value=s.end||'23:00';$('#username').value=s.user||'malinovskym';$('#note').value=s.note||''}catch{}}
$('#resetButton').onclick=()=>{localStorage.removeItem('teamSwapState');location.reload()};load();renderCalendars();syncSkills();document.fonts.ready.then(drawCard);drawCard();
