const $=s=>document.querySelector(s);const pad=n=>String(n).padStart(2,'0');
const today=new Date();today.setHours(0,0,0,0);const initialReplace=new Date(today);initialReplace.setDate(today.getDate()+4);
const state={replaceDate:initialReplace,available:[],skills:['Голосовая поддержка L1'],customSkills:[],customOpen:false,viewReplace:new Date(today.getFullYear(),today.getMonth(),1),viewAvailable:new Date(today.getFullYear(),today.getMonth(),1)};
const months=['январь','февраль','март','апрель','май','июнь','июль','август','сентябрь','октябрь','ноябрь','декабрь'];
const fmt=d=>`${pad(d.getDate())}.${pad(d.getMonth()+1)}.${String(d.getFullYear()).slice(-2)}`;const key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
function monthMarkup(view,selected,multi=false){const y=view.getFullYear(),m=view.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();let html=`<div class="calendar-header"><button class="calendar-nav prev" type="button" aria-label="Предыдущий месяц">‹</button><div class="calendar-title">${months[m]} ${y}</div><button class="calendar-nav next" type="button" aria-label="Следующий месяц">›</button></div><div class="calendar-grid">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<span class="weekday">${x}</span>`).join('')}`;for(let i=0;i<first;i++)html+='<span></span>';for(let d=1;d<=days;d++){const date=new Date(y,m,d),isPast=date<today,isSelected=multi?selected.includes(key(date)):selected&&key(date)===key(selected);html+=`<button type="button" class="day ${isSelected?'selected':''} ${key(date)===key(today)?'today':''} ${isPast?'disabled':''}" data-date="${key(date)}" ${isPast?'disabled':''}>${d}</button>`}return html+'</div>'}
function parseDate(v){const [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)}
function bindCalendar(root,type){root.querySelector('.prev').onclick=()=>{state[type].setMonth(state[type].getMonth()-1);renderCalendars()};root.querySelector('.next').onclick=()=>{state[type].setMonth(state[type].getMonth()+1);renderCalendars()};root.querySelectorAll('.day:not(.disabled)').forEach(b=>b.onclick=()=>{const d=parseDate(b.dataset.date);if(type==='viewReplace'){state.replaceDate=d;$('#replaceCalendar').hidden=true}else{const k=key(d),i=state.available.indexOf(k);i>=0?state.available.splice(i,1):state.available.push(k);state.available.sort()}renderCalendars();drawCard();save()})}
function renderCalendars(){const pop=$('#replaceCalendar'),inline=$('#availableCalendar');pop.innerHTML=monthMarkup(state.viewReplace,state.replaceDate);inline.innerHTML=monthMarkup(state.viewAvailable,state.available,true);bindCalendar(pop,'viewReplace');bindCalendar(inline,'viewAvailable');$('#replaceDateText').textContent=new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(state.replaceDate);$('#dateCounter').textContent=`${state.available.length} выбрано`}
$('#replaceDateButton').onclick=()=>$('#replaceCalendar').hidden=!$('#replaceCalendar').hidden;document.addEventListener('click',e=>{if(!e.target.closest('.field'))$('#replaceCalendar').hidden=true});
function syncSkills(){document.querySelectorAll('[data-skill]').forEach(b=>b.classList.toggle('active',state.skills.includes(b.dataset.skill)));$('#customSkillButton').classList.toggle('active',state.customOpen||state.customSkills.length>0);$('#customSkillWrap').hidden=!state.customOpen;$('#customSkillList').innerHTML=state.customSkills.map((s,i)=>`<button type="button" class="custom-skill-tag" data-index="${i}" title="Удалить">${s}</button>`).join('');drawCard();save()}
$('#skillOptions').onclick=e=>{const b=e.target.closest('.skill-option');if(!b)return;if(b.id==='customSkillButton'){state.customOpen=!state.customOpen}else{const s=b.dataset.skill,i=state.skills.indexOf(s);i>=0?state.skills.splice(i,1):state.skills.push(s)}syncSkills()};
function addCustom(){const input=$('#customSkill'),v=input.value.trim();if(v&&!state.customSkills.includes(v)){state.customSkills.push(v);input.value='';syncSkills()}}
$('#addCustomSkill').onclick=addCustom;$('#customSkill').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addCustom()}});$('#customSkillList').onclick=e=>{const b=e.target.closest('.custom-skill-tag');if(!b)return;state.customSkills.splice(Number(b.dataset.index),1);syncSkills()};
['startTime','endTime','username','note'].forEach(id=>$('#'+id).addEventListener('input',()=>{drawCard();save()}));
function rounded(ctx,x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function fitText(ctx,text,max,width,weight=700){let size=max;do{ctx.font=`${weight} ${size}px Manrope,Arial`;size--}while(ctx.measureText(text).width>width&&size>16);return size+1}
function lineIcon(ctx,type,x,y){ctx.save();ctx.translate(x,y);ctx.strokeStyle='#111';ctx.fillStyle='#111';ctx.lineWidth=5;ctx.lineCap='round';ctx.lineJoin='round';if(type==='headset'){ctx.beginPath();ctx.arc(0,0,25,Math.PI,0);ctx.stroke();ctx.strokeRect(-29,0,9,22);ctx.strokeRect(20,0,9,22);ctx.beginPath();ctx.moveTo(29,18);ctx.quadraticCurveTo(29,34,10,34);ctx.stroke();rounded(ctx,4,29,14,9,4,'#ffc400')}else if(type==='clock'){ctx.beginPath();ctx.arc(0,4,29,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(0,4);ctx.lineTo(0,-14);ctx.moveTo(0,4);ctx.lineTo(16,14);ctx.strokeStyle='#f5b900';ctx.stroke()}else{rounded(ctx,-27,-24,54,49,9,null,'#111');ctx.beginPath();ctx.moveTo(-15,-32);ctx.lineTo(-15,-17);ctx.moveTo(15,-32);ctx.lineTo(15,-17);ctx.stroke();ctx.fillStyle='#f5b900';[-13,0,13].forEach(dx=>ctx.fillRect(dx-3,-3,6,6));[-13,0,13].forEach(dx=>ctx.fillRect(dx-3,11,6,6))}ctx.restore()}
function drawCard(){const c=$('#cardCanvas'),ctx=c.getContext('2d'),allSkills=[...state.skills,...state.customSkills];ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#f7f6f2';ctx.fillRect(0,0,1200,760);rounded(ctx,24,24,1152,712,34,'#fff');ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.fillStyle='#f33';ctx.font='800 52px Manrope,Arial';ctx.fillText('Y',62,88);ctx.fillStyle='#111';ctx.fillText('andex',100,88);ctx.font='400 51px Manrope,Arial';ctx.fillText('Team',270,88);rounded(ctx,914,48,206,52,26,'#f4f3ef');ctx.fillStyle='#666';ctx.font='700 17px Manrope,Arial';ctx.fillText('ОБМЕН СМЕНАМИ',940,80);
const g=ctx.createLinearGradient(0,130,0,270);g.addColorStop(0,'#ffd53d');g.addColorStop(1,'#ffbd08');rounded(ctx,54,128,1092,142,26,g);ctx.fillStyle='#111';ctx.font='800 43px Manrope,Arial';ctx.fillText('Ищу замену',88,186);ctx.font='500 24px Manrope,Arial';ctx.fillText('на рабочий день',89,224);rounded(ctx,769,151,335,96,22,'#fff');lineIcon(ctx,'calendar',817,199);ctx.font='800 40px Manrope,Arial';ctx.fillText(fmt(state.replaceDate),868,213);
rounded(ctx,54,290,1092,324,25,'#faf9f6');ctx.strokeStyle='#e5e2d8';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(105,397);ctx.lineTo(1095,397);ctx.moveTo(105,493);ctx.lineTo(1095,493);ctx.stroke();const rows=[{icon:'headset',label:'НАВЫКИ',value:allSkills.length?allSkills.join('  •  '):'Не выбраны'},{icon:'clock',label:'СМЕНА',value:`${$('#startTime').value||'—'} — ${$('#endTime').value||'—'}`}];rows.forEach((r,i)=>{const cy=346+i*98;rounded(ctx,75,cy-35,70,70,20,'#fff0ba');lineIcon(ctx,r.icon,110,cy-3);ctx.fillStyle='#89857a';ctx.font='800 14px Manrope,Arial';ctx.fillText(r.label,174,cy-8);ctx.fillStyle='#111';ctx.font=`700 ${fitText(ctx,r.value,25,865)}px Manrope,Arial`;ctx.fillText(r.value,174,cy+25)});
rounded(ctx,75,516,70,70,20,'#fff0ba');lineIcon(ctx,'calendar',110,552);ctx.fillStyle='#89857a';ctx.font='800 14px Manrope,Arial';ctx.fillText('МОГУ ВЫЙТИ',174,539);let dx=174;const dates=state.available.slice(0,10).map(v=>parseDate(v).getDate());if(!dates.length){ctx.fillStyle='#aaa';ctx.font='600 21px Manrope,Arial';ctx.fillText('Выберите даты в календаре',174,572)}else dates.forEach(n=>{rounded(ctx,dx,550,55,39,11,'#fff','#f5b900');ctx.fillStyle='#111';ctx.textAlign='center';ctx.font='800 20px Manrope,Arial';ctx.fillText(n,dx+27.5,577);ctx.textAlign='left';dx+=65});rounded(ctx,54,632,1092,78,23,'#1e1f1d');ctx.fillStyle='#ffc800';ctx.font='30px Manrope,Arial';ctx.fillText('★',82,683);const note=$('#note').value||'Буду благодарен за обмен!';ctx.fillStyle='#fff';ctx.font=`600 ${fitText(ctx,note,24,620,600)}px Manrope,Arial`;ctx.fillText(note,128,681);ctx.strokeStyle='#5b5c58';ctx.beginPath();ctx.moveTo(845,650);ctx.lineTo(845,692);ctx.stroke();ctx.fillStyle='#ffc800';ctx.font='25px Manrope,Arial';ctx.fillText('@',878,680);const user=$('#username').value||'username';ctx.fillStyle='#fff';ctx.font=`700 ${fitText(ctx,user,23,195)}px Manrope,Arial`;ctx.fillText(user,912,680)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2300)}
$('#downloadButton').onclick=()=>{const a=document.createElement('a');a.download=`замена-${key(state.replaceDate)}.png`;a.href=$('#cardCanvas').toDataURL('image/png');a.click();toast('Карточка скачана')};$('#copyButton').onclick=async()=>{try{const blob=await new Promise(r=>$('#cardCanvas').toBlob(r,'image/png'));await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);toast('Карточка скопирована')}catch{toast('Копирование не поддерживается — скачайте PNG')}};
function save(){localStorage.setItem('teamSwapState',JSON.stringify({replace:key(state.replaceDate),available:state.available,skills:state.skills,customSkills:state.customSkills,start:$('#startTime').value,end:$('#endTime').value,user:$('#username').value,note:$('#note').value}))}
function load(){try{const s=JSON.parse(localStorage.getItem('teamSwapState'));if(!s)return;state.replaceDate=parseDate(s.replace);state.available=s.available||[];state.skills=s.skills||(s.skill?[s.skill]:state.skills);state.customSkills=s.customSkills||(s.customSkill?[s.customSkill]:[]);$('#startTime').value=s.start||'11:00';$('#endTime').value=s.end||'23:00';$('#username').value=s.user||'malinovskym';$('#note').value=s.note||''}catch{}}
$('#resetButton').onclick=()=>{localStorage.removeItem('teamSwapState');location.reload()};load();renderCalendars();syncSkills();document.fonts.ready.then(drawCard);drawCard();
